# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/briansena/Uni/MH/P1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/briansena/Uni/MH/P1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/briansena/Uni/MH/P1/CMakeFiles /home/briansena/Uni/MH/P1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/briansena/Uni/MH/P1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Fast1NN

# Build rule for target.
Fast1NN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fast1NN
.PHONY : Fast1NN

# fast build rule for target.
Fast1NN/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/build
.PHONY : Fast1NN/fast

#=============================================================================
# Target rules for targets named FastGreedy

# Build rule for target.
FastGreedy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FastGreedy
.PHONY : FastGreedy

# fast build rule for target.
FastGreedy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/build
.PHONY : FastGreedy/fast

#=============================================================================
# Target rules for targets named LSalg

# Build rule for target.
LSalg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LSalg
.PHONY : LSalg

# fast build rule for target.
LSalg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/build
.PHONY : LSalg/fast

src/Fast1NN.o: src/Fast1NN.cpp.o

.PHONY : src/Fast1NN.o

# target to build an object file
src/Fast1NN.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/src/Fast1NN.cpp.o
.PHONY : src/Fast1NN.cpp.o

src/Fast1NN.i: src/Fast1NN.cpp.i

.PHONY : src/Fast1NN.i

# target to preprocess a source file
src/Fast1NN.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/src/Fast1NN.cpp.i
.PHONY : src/Fast1NN.cpp.i

src/Fast1NN.s: src/Fast1NN.cpp.s

.PHONY : src/Fast1NN.s

# target to generate assembly for a file
src/Fast1NN.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/src/Fast1NN.cpp.s
.PHONY : src/Fast1NN.cpp.s

src/LSalg.o: src/LSalg.cpp.o

.PHONY : src/LSalg.o

# target to build an object file
src/LSalg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/src/LSalg.cpp.o
.PHONY : src/LSalg.cpp.o

src/LSalg.i: src/LSalg.cpp.i

.PHONY : src/LSalg.i

# target to preprocess a source file
src/LSalg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/src/LSalg.cpp.i
.PHONY : src/LSalg.cpp.i

src/LSalg.s: src/LSalg.cpp.s

.PHONY : src/LSalg.s

# target to generate assembly for a file
src/LSalg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/src/LSalg.cpp.s
.PHONY : src/LSalg.cpp.s

src/greedyFast.o: src/greedyFast.cpp.o

.PHONY : src/greedyFast.o

# target to build an object file
src/greedyFast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/src/greedyFast.cpp.o
.PHONY : src/greedyFast.cpp.o

src/greedyFast.i: src/greedyFast.cpp.i

.PHONY : src/greedyFast.i

# target to preprocess a source file
src/greedyFast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/src/greedyFast.cpp.i
.PHONY : src/greedyFast.cpp.i

src/greedyFast.s: src/greedyFast.cpp.s

.PHONY : src/greedyFast.s

# target to generate assembly for a file
src/greedyFast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/src/greedyFast.cpp.s
.PHONY : src/greedyFast.cpp.s

src/mytools.o: src/mytools.cpp.o

.PHONY : src/mytools.o

# target to build an object file
src/mytools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/src/mytools.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/src/mytools.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/src/mytools.cpp.o
.PHONY : src/mytools.cpp.o

src/mytools.i: src/mytools.cpp.i

.PHONY : src/mytools.i

# target to preprocess a source file
src/mytools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/src/mytools.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/src/mytools.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/src/mytools.cpp.i
.PHONY : src/mytools.cpp.i

src/mytools.s: src/mytools.cpp.s

.PHONY : src/mytools.s

# target to generate assembly for a file
src/mytools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fast1NN.dir/build.make CMakeFiles/Fast1NN.dir/src/mytools.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastGreedy.dir/build.make CMakeFiles/FastGreedy.dir/src/mytools.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSalg.dir/build.make CMakeFiles/LSalg.dir/src/mytools.cpp.s
.PHONY : src/mytools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Fast1NN"
	@echo "... FastGreedy"
	@echo "... LSalg"
	@echo "... src/Fast1NN.o"
	@echo "... src/Fast1NN.i"
	@echo "... src/Fast1NN.s"
	@echo "... src/LSalg.o"
	@echo "... src/LSalg.i"
	@echo "... src/LSalg.s"
	@echo "... src/greedyFast.o"
	@echo "... src/greedyFast.i"
	@echo "... src/greedyFast.s"
	@echo "... src/mytools.o"
	@echo "... src/mytools.i"
	@echo "... src/mytools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

